-- Describe SCAMUESTRA
CREATE TABLE scamuestra (
    "IdMuestra" PK INTEGER NOT NULL,
    "IdPersona" INTEGER,
    "IdEspecie" INTEGER DEFAULT (NULL),
    "IdCentro" INTEGER DEFAULT (1),
    "IdDoctor" INTEGER DEFAULT (1),
    "Referencia" TEXT NOT NULL,
    "FechaAnalisis" TEXT,
    "HoraAnalisis" TEXT,
    "Volumen" NULL DEFAULT (2.5),
    "FechaObtencion" TEXT,
    "HoraObtencion" TEXT,
    "HoraEntrega" TEXT,
    "IdMetodoObtencion" INTEGER,
    "DiasAbstinencia" INTEGER DEFAULT (3),
    "pH" REAL DEFAULT (7.5),
    "Temperatura" INTEGER DEFAULT (37),
    "IdColor" INTEGER DEFAULT (1),
    "IdViscosidad" INTEGER DEFAULT (1),
    "IdLicuefaccion" INTEGER DEFAULT (1),
    "IdAspecto" INTEGER DEFAULT (1),
    "IdOlor" INTEGER DEFAULT (1),
    "IdAglutinaciones" INTEGER DEFAULT (1),
    "IdOtrasPropiedades" INTEGER DEFAULT (1),
    "Observaciones" TEXT DEFAULT (null),
    "local" INTEGER DEFAULT (1),
    "Other" TEXT DEFAULT ('{null}'),
    "Confirmed" INTEGER DEFAULT (0),
    "Optional1" TEXT DEFAULT (NULL),
    "Optional2" TEXT DEFAULT (NULL),
    "Optional3" TEXT DEFAULT (NULL),
    "Optional4" TEXT DEFAULT (NULL),
    "Optional5" TEXT DEFAULT (NULL),
    "Optional6" TEXT DEFAULT (NULL),
    "Optional7" TEXT DEFAULT (NULL),
    "Optional8" TEXT DEFAULT (NULL),
    "Optional9" TEXT DEFAULT (NULL),
    "Optional10" TEXT DEFAULT (NULL),
    "IdCollection1" INTEGER DEFAULT (1),
    "IdCollection2" INTEGER DEFAULT (1)
)